apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: petclinic 
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: quay.io/schennu/ieopetclinic:v1 
