apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: petclinic 
spec:
  template:
    spec:
      containers:
      - image: quay.io/schennu/ieopetclinic:v1 
        livenessProbe:
          httpGet:
            path: /healthz
        readinessProbe:
          httpGet:
            path: /healthz
